# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMye3tKARiVWHSyh86J6WuE5nTnO4W-X
"""

#logic building task 1
#1.User Login Check
username=input("Enter the username:")
Password=int(input("Enter the password:"))
if username=="admin" and Password==1234:
  print("Login Succesful")
else:
  print("Invalid Credentials")

#2.Pass/ Fail Analyzer
marks=[45,78,90,33,60]
ppass=0
fail=0
for i in marks:
  if i>=50:
    ppass+=1
  else:
    fail+=1
print(f"the total number of pass studens is {ppass} and the total number of fail students is {fail}")

#3.Simple Data Cleaner
names=[" Alice","bob","CHARLIE"]
m=[]
for i in names:
  n=i.lower()
  s=n.strip()
  m.append(s)
print(m)

#4.Message Length Analyzer
messages=["Hi","Welcome to the platform","OK"]
for i in messages:
  m=len(i)
  print(f"message:{i}")
  if m>10:
    print(f"Length:{m}, Length greater than 10 hence flagged")
  else:
    print(f"Length:{m}")

#Error Message Detector
logs = ["INFO", "ERROR", "WARNING", "ERROR"]
count=0
for i in logs:
  if i=="ERROR":
    count+=1
print("total error count:",count)

"""Really Apologize for the late submission. I can assure you that none of this was done by using AI and everything was done by my own"""